In [711]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [712]:
df = pd.read_csv("automobiledata.csv")
df

name  mpg  cylinders  displacement  horsepower  \
0      chevrolet chevelle malibu   18          8         307.0       130.0   
1              buick skylark 320   15          8         350.0       165.0   
2             plymouth satellite   18          8         318.0       150.0   
3                  amc rebel sst   16          8         304.0       150.0   
4                    ford torino   17          8         302.0       140.0   
..                           ...  ...        ...           ...         ...   
94  chrysler new yorker brougham   13          8         440.0       215.0   
95      buick electra 225 custom   12          8         455.0       225.0   
96       amc ambassador brougham   13          8         360.0       175.0   
97              plymouth valiant   18          6         225.0       105.0   
98         chevrolet nova custom   16          6         250.0       100.0   

    weight  acceleration  model_year origin  
0     3504          12.0          70    usa  
1     3693          11.5          70    usa  
2     3436          11.0          70    usa  
3     3433          12.0          70    usa  
4     3449          10.5          70    usa  
..     ...           ...         ...    ...  
94    4735          11.0          73    usa  
95    4951          11.0          73    usa  
96    3821          11.0          73    usa  
97    3121          16.5          73    usa  
98    3278          18.0          73    usa  

[99 rows x 9 columns]

In [713]:
df.size

891

In [714]:
df.shape

(99, 9)

In [715]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          99 non-null     object 
 1   mpg           99 non-null     int64  
 2   cylinders     99 non-null     int64  
 3   displacement  99 non-null     float64
 4   horsepower    98 non-null     float64
 5   weight        99 non-null     int64  
 6   acceleration  99 non-null     float64
 7   model_year    99 non-null     int64  
 8   origin        99 non-null     object 
dtypes: float64(3), int64(4), object(2)
memory usage: 7.1+ KB


In [716]:
df.describe()

mpg  cylinders  displacement  horsepower       weight  \
count  99.000000  99.000000     99.000000   98.000000    99.000000   
mean   18.434343   6.292929    252.530303  130.357143  3331.717172   
std     5.843471   1.853031    123.580652   47.669881   971.120561   
min     9.000000   3.000000     70.000000   46.000000  1613.000000   
25%    14.000000   4.000000    120.000000   90.000000  2373.500000   
50%    17.000000   8.000000    302.000000  130.000000  3433.000000   
75%    23.000000   8.000000    350.000000  165.000000  4223.000000   
max    35.000000   8.000000    455.000000  225.000000  5140.000000   

       acceleration  model_year  
count     99.000000   99.000000  
mean      14.202020   71.272727  
std        3.019426    1.038230  
min        8.000000   70.000000  
25%       12.000000   70.000000  
50%       14.000000   71.000000  
75%       15.750000   72.000000  
max       23.500000   73.000000

In [717]:
df.isnull().sum()

name            0
mpg             0
cylinders       0
displacement    0
horsepower      1
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [718]:
# fill 1 missing value

In [719]:
df['horsepower'].fillna(value=130.357143,inplace=True)
df

name  mpg  cylinders  displacement  horsepower  \
0      chevrolet chevelle malibu   18          8         307.0       130.0   
1              buick skylark 320   15          8         350.0       165.0   
2             plymouth satellite   18          8         318.0       150.0   
3                  amc rebel sst   16          8         304.0       150.0   
4                    ford torino   17          8         302.0       140.0   
..                           ...  ...        ...           ...         ...   
94  chrysler new yorker brougham   13          8         440.0       215.0   
95      buick electra 225 custom   12          8         455.0       225.0   
96       amc ambassador brougham   13          8         360.0       175.0   
97              plymouth valiant   18          6         225.0       105.0   
98         chevrolet nova custom   16          6         250.0       100.0   

    weight  acceleration  model_year origin  
0     3504          12.0          70    usa  
1     3693          11.5          70    usa  
2     3436          11.0          70    usa  
3     3433          12.0          70    usa  
4     3449          10.5          70    usa  
..     ...           ...         ...    ...  
94    4735          11.0          73    usa  
95    4951          11.0          73    usa  
96    3821          11.0          73    usa  
97    3121          16.5          73    usa  
98    3278          18.0          73    usa  

[99 rows x 9 columns]

In [720]:
df.isnull().sum().sum()

0

# applye Label Encoding 

In [721]:
from sklearn.preprocessing import LabelEncoder

In [722]:
le_enc=df[["origin"]]

In [723]:
le=LabelEncoder()

In [724]:
le.fit_transform(le_enc["origin"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0,
       0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0, 2, 1, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [725]:
le_enc['origin_df']=le.fit_transform(le_enc["origin"])
le_enc

C:\Users\Admin\AppData\Local\Temp\ipykernel_2232\1482975260.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  le_enc['origin_df']=le.fit_transform(le_enc["origin"])


origin  origin_df
0     usa          2
1     usa          2
2     usa          2
3     usa          2
4     usa          2
..    ...        ...
94    usa          2
95    usa          2
96    usa          2
97    usa          2
98    usa          2

[99 rows x 2 columns]

In [726]:
df['origin']=df['origin'].map({'euroup':0, 'japan':1, 'usa':2})
df.head()

name  mpg  cylinders  displacement  horsepower  \
0  chevrolet chevelle malibu   18          8         307.0       130.0   
1          buick skylark 320   15          8         350.0       165.0   
2         plymouth satellite   18          8         318.0       150.0   
3              amc rebel sst   16          8         304.0       150.0   
4                ford torino   17          8         302.0       140.0   

   weight  acceleration  model_year  origin  
0    3504          12.0          70     2.0  
1    3693          11.5          70     2.0  
2    3436          11.0          70     2.0  
3    3433          12.0          70     2.0  
4    3449          10.5          70     2.0

# Using one hot encoding

In [728]:
from sklearn.preprocessing import OneHotEncoder

In [729]:
oh_enc = OneHotEncoder(sparse=False,)
#Will return sparse matrix if set True else will return an array
# It provide output in Numpy array

In [730]:
#This method simultaneously performs fit and transform operations on the input data and converts the data points
oh_enc_arr = oh_enc.fit_transform(df[['name']])# categor

oh_enc_arr

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [731]:
dummy_df=pd.get_dummies(df)
dummy_df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  model_year  \
0   18          8         307.0       130.0    3504          12.0          70   
1   15          8         350.0       165.0    3693          11.5          70   
2   18          8         318.0       150.0    3436          11.0          70   
3   16          8         304.0       150.0    3433          12.0          70   
4   17          8         302.0       140.0    3449          10.5          70   

   origin  name_amc ambassador brougham  name_amc ambassador dpl  ...  \
0     2.0                         False                    False  ...   
1     2.0                         False                    False  ...   
2     2.0                         False                    False  ...   
3     2.0                         False                    False  ...   
4     2.0                         False                    False  ...   

   name_toyota corolla 1600 (sw)  name_toyota corona  \
0                          False               False   
1                          False               False   
2                          False               False   
3                          False               False   
4                          False               False   

   name_toyota corona hardtop  name_toyota corona mark ii  \
0                       False                       False   
1                       False                       False   
2                       False                       False   
3                       False                       False   
4                       False                       False   

   name_toyouta corona mark ii (sw)  name_volkswagen 1131 deluxe sedan  \
0                             False                              False   
1                             False                              False   
2                             False                              False   
3                             False                              False   
4                             False                              False   

   name_volkswagen 411 (sw)  name_volkswagen model 111  \
0                     False                      False   
1                     False                      False   
2                     False                      False   
3                     False                      False   
4                     False                      False   

   name_volkswagen type 3  name_volvo 145e (sw)  
0                   False                 False  
1                   False                 False  
2                   False                 False  
3                   False                 False  
4                   False                 False  

[5 rows x 96 columns]

In [732]:
dummy_df.keys()

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name_amc ambassador brougham',
       'name_amc ambassador dpl', 'name_amc ambassador sst',
       'name_amc gremlin', 'name_amc hornet',
       'name_amc hornet sportabout (sw)', 'name_amc matador',
       'name_amc matador (sw)', 'name_amc rebel sst', 'name_audi 100 ls',
       'name_bmw 2002', 'name_buick century 350',
       'name_buick electra 225 custom', 'name_buick estate wagon (sw)',
       'name_buick lesabre custom', 'name_buick skylark 320',
       'name_chevrolet caprice classic',
       'name_chevrolet chevelle concours (sw)',
       'name_chevrolet chevelle malibu', 'name_chevrolet impala',
       'name_chevrolet malibu', 'name_chevrolet monte carlo',
       'name_chevrolet nova custom', 'name_chevrolet vega',
       'name_chevrolet vega (sw)', 'name_chevrolet vega 2300',
       'name_chevy c20', 'name_chrysler new yorker brougham',
       'name_chrysler new

In [733]:
oh_enc_df = pd.DataFrame(oh_enc_arr, columns=[ 'name_amc ambassador brougham',
       'name_amc ambassador dpl', 'name_amc ambassador sst',
       'name_amc gremlin', 'name_amc hornet',
       'name_amc hornet sportabout (sw)', 'name_amc matador',
       'name_amc matador (sw)', 'name_amc rebel sst', 'name_audi 100 ls',
       'name_bmw 2002', 'name_buick century 350',
       'name_buick electra 225 custom', 'name_buick estate wagon (sw)',
       'name_buick lesabre custom', 'name_buick skylark 320',
       'name_chevrolet caprice classic',
       'name_chevrolet chevelle concours (sw)',
       'name_chevrolet chevelle malibu', 'name_chevrolet impala',
       'name_chevrolet malibu', 'name_chevrolet monte carlo',
       'name_chevrolet nova custom', 'name_chevrolet vega',
       'name_chevrolet vega (sw)', 'name_chevrolet vega 2300',
       'name_chevy c20', 'name_chrysler new yorker brougham',
       'name_chrysler newport royal', 'name_datsun 1200',
       'name_datsun 510 (sw)', 'name_datsun pl510', 'name_dodge challenger se',
       'name_dodge colt (sw)', 'name_dodge colt hardtop',
       'name_dodge coronet custom', 'name_dodge d200',
       'name_dodge monaco (sw)', 'name_fiat 124b',
       'name_ford country squire (sw)', 'name_ford f250',
       'name_ford galaxie 500', 'name_ford gran torino',
       'name_ford gran torino (sw)', 'name_ford ltd', 'name_ford maverick',
       'name_ford mustang', 'name_ford pinto', 'name_ford pinto (sw)',
       'name_ford pinto runabout', 'name_ford torino', 'name_ford torino 500',
       'name_hi 1200d', 'name_mazda rx2 coupe', 'name_mercury capri 2000',
       'name_mercury marquis', 'name_mercury marquis brougham',
       'name_oldsmobile delta 88 royale', 'name_opel 1900', 'name_peugeot 304',
       'name_peugeot 504', 'name_peugeot 504 (sw)', 'name_plymouth cuda 340',
       'name_plymouth cricket', 'name_plymouth duster',
       'name_plymouth fury gran sedan', 'name_plymouth fury iii',
       'name_plymouth satellite', 'name_plymouth satellite custom',
       'name_plymouth satellite custom (sw)', 'name_plymouth valiant',
       'name_pontiac catalina', 'name_pontiac catalina brougham',
       'name_pontiac firebird', 'name_pontiac safari (sw)',
       'name_renault 12 (sw)', 'name_saab 99e', 'name_toyota corolla 1200',
       'name_toyota corolla 1600 (sw)', 'name_toyota corona',
       'name_toyota corona hardtop', 'name_toyota corona mark ii',
       'name_toyouta corona mark ii (sw)', 'name_volkswagen 1131 deluxe sedan',
       'name_volkswagen 411 (sw)', 'name_volkswagen model 111',
       'name_volkswagen type 3', 'name_volvo 145e (sw)'])
oh_enc_df       

name_amc ambassador brougham  name_amc ambassador dpl  \
0                            0.0                      0.0   
1                            0.0                      0.0   
2                            0.0                      0.0   
3                            0.0                      0.0   
4                            0.0                      0.0   
..                           ...                      ...   
94                           0.0                      0.0   
95                           0.0                      0.0   
96                           1.0                      0.0   
97                           0.0                      0.0   
98                           0.0                      0.0   

    name_amc ambassador sst  name_amc gremlin  name_amc hornet  \
0                       0.0               0.0              0.0   
1                       0.0               0.0              0.0   
2                       0.0               0.0              0.0   
3                       0.0               0.0              0.0   
4                       0.0               0.0              0.0   
..                      ...               ...              ...   
94                      0.0               0.0              0.0   
95                      0.0               0.0              0.0   
96                      0.0               0.0              0.0   
97                      0.0               0.0              0.0   
98                      0.0               0.0              0.0   

    name_amc hornet sportabout (sw)  name_amc matador  name_amc matador (sw)  \
0                               0.0               0.0                    0.0   
1                               0.0               0.0                    0.0   
2                               0.0               0.0                    0.0   
3                               0.0               0.0                    0.0   
4                               0.0               0.0                    0.0   
..                              ...               ...                    ...   
94                              0.0               0.0                    0.0   
95                              0.0               0.0                    0.0   
96                              0.0               0.0                    0.0   
97                              0.0               0.0                    0.0   
98                              0.0               0.0                    0.0   

    name_amc rebel sst  name_audi 100 ls  ...  name_toyota corolla 1600 (sw)  \
0                  0.0               0.0  ...                            0.0   
1                  0.0               0.0  ...                            0.0   
2                  0.0               0.0  ...                            0.0   
3                  1.0               0.0  ...                            0.0   
4                  0.0               0.0  ...                            0.0   
..                 ...               ...  ...                            ...   
94                 0.0               0.0  ...                            0.0   
95                 0.0               0.0  ...                            0.0   
96                 0.0               0.0  ...                            0.0   
97                 0.0               0.0  ...                            0.0   
98                 0.0               0.0  ...                            0.0   

    name_toyota corona  name_toyota corona hardtop  \
0                  0.0                         0.0   
1                  0.0                         0.0   
2                  0.0                         0.0   
3                  0.0                         0.0   
4                  0.0                         0.0   
..                 ...                         ...   
94                 0.0                         0.0   
95                 0.0                         0.0   
96                 0.0                         0.0   
97              

In [734]:
df['name'] = oh_enc_df[['name_amc ambassador brougham']].copy()



df['name']

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ... 
94    0.0
95    0.0
96    1.0
97    0.0
98    0.0
Name: name, Length: 99, dtype: float64

In [735]:
df3=df['name']
df3

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ... 
94    0.0
95    0.0
96    1.0
97    0.0
98    0.0
Name: name, Length: 99, dtype: float64

In [736]:
print("After updating the 'final' with 'df'.............................")
df.update(df3)
df

After updating the 'final' with 'df'.............................


name  mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    0.0   18          8         307.0       130.0    3504          12.0   
1    0.0   15          8         350.0       165.0    3693          11.5   
2    0.0   18          8         318.0       150.0    3436          11.0   
3    0.0   16          8         304.0       150.0    3433          12.0   
4    0.0   17          8         302.0       140.0    3449          10.5   
..   ...  ...        ...           ...         ...     ...           ...   
94   0.0   13          8         440.0       215.0    4735          11.0   
95   0.0   12          8         455.0       225.0    4951          11.0   
96   1.0   13          8         360.0       175.0    3821          11.0   
97   0.0   18          6         225.0       105.0    3121          16.5   
98   0.0   16          6         250.0       100.0    3278          18.0   

    model_year  origin  
0           70     2.0  
1           70     2.0  
2           70     2.0  
3           70     2.0  
4           70     2.0  
..         ...     ...  
94          73     2.0  
95          73     2.0  
96          73     2.0  
97          73     2.0  
98          73     2.0  

[99 rows x 9 columns]

# split data

In [737]:
x=df.drop('origin',axis=1)
y=df['origin']
print('Shape of x=',x.shape)
print('Shape of y=',y.shape) 

Shape of x= (99, 8)
Shape of y= (99,)


In [738]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size= 0.2,random_state=2020)
print('Shape of x_train =', x_train.shape)
print('Shape of y_train =', y_train.shape)
print('Shape of x_test =', x_test.shape)
print('Shape of y_test =', y_test.shape)

Shape of x_train = (79, 8)
Shape of y_train = (79,)
Shape of x_test = (20, 8)
Shape of y_test = (20,)


In [739]:
mean_y_train = y_train.mean()
y_train.fillna(mean_y_train, inplace=True)
y_train

31    1.000000
17    2.000000
59    1.848485
53    1.000000
13    2.000000
        ...   
91    2.000000
98    2.000000
67    2.000000
8     2.000000
96    2.000000
Name: origin, Length: 79, dtype: float64

In [740]:
y_test.isnull().sum()

1

In [741]:
mean_y_test = y_test.mean()
y_test.fillna(mean_y_test, inplace=True)
mean_y_test

1.9473684210526316

In [742]:
mean_y_train=y_train

In [743]:
mean_y_test=y_test

In [744]:
x_train

name  mpg  cylinders  displacement  horsepower  weight  acceleration  \
31   0.0   25          4         113.0        95.0    2228          14.0   
17   0.0   21          6         200.0        85.0    2587          16.0   
59   0.0   23          4          97.0        54.0    2254          23.5   
53   0.0   31          4          71.0        65.0    1773          19.0   
13   0.0   14          8         455.0       225.0    3086          10.0   
..   ...  ...        ...           ...         ...     ...           ...   
91   0.0   13          8         400.0       150.0    4464          12.0   
98   0.0   16          6         250.0       100.0    3278          18.0   
67   0.0   11          8         429.0       208.0    4633          11.0   
8    0.0   14          8         455.0       225.0    4425          10.0   
96   1.0   13          8         360.0       175.0    3821          11.0   

    model_year  
31          71  
17          70  
59          72  
53          71  
13          70  
..         ...  
91          73  
98          73  
67          72  
8           70  
96          73  

[79 rows x 8 columns]

In [745]:
x_test

name  mpg  cylinders  displacement  horsepower  weight  acceleration  \
47   0.0   19          6         250.0       100.0    3282          15.0   
12   0.0   15          8         400.0       150.0    3761           9.5   
61   0.0   21          4         122.0        86.0    2226          16.5   
23   0.0   26          4         121.0       113.0    2234          12.5   
70   0.0   13          8         400.0       190.0    4422          12.5   
68   0.0   13          8         350.0       155.0    4502          13.5   
43   0.0   13          8         400.0       170.0    4746          12.0   
35   0.0   17          6         250.0       100.0    3329          15.5   
60   0.0   20          4         140.0        90.0    2408          19.5   
87   0.0   13          8         350.0       145.0    3988          13.0   
40   0.0   14          8         351.0       153.0    4154          13.5   
57   0.0   24          4         113.0        95.0    2278          15.5   
49   0.0   23          4         122.0        86.0    2220          14.0   
58   0.0   25          4          97.5        80.0    2126          17.0   
7    0.0   14          8         440.0       215.0    4312           8.5   
88   0.0   14          8         302.0       137.0    4042          14.5   
25   0.0   10          8         360.0       215.0    4615          14.0   
37   0.0   18          6         232.0       100.0    3288          15.5   
64   0.0   15          8         318.0       150.0    4135          13.5   
45   0.0   18          6         258.0       110.0    2962          13.5   

    model_year  
47          71  
12          70  
61          72  
23          70  
70          72  
68          72  
43          71  
35          71  
60          72  
87          73  
40          71  
57          72  
49          71  
58          72  
7           70  
88          73  
25          70  
37          71  
64          72  
45          71

In [746]:
# fill Nan in y

y_train_filled= y_train.fillna(y_train.mean())
y_test_filled= y_test.fillna(y_test.mean())

In [747]:
y_train

31    1.000000
17    2.000000
59    1.848485
53    1.000000
13    2.000000
        ...   
91    2.000000
98    2.000000
67    2.000000
8     2.000000
96    2.000000
Name: origin, Length: 79, dtype: float64

In [748]:
y_test

47    2.000000
12    2.000000
61    2.000000
23    1.947368
70    2.000000
68    2.000000
43    2.000000
35    2.000000
60    2.000000
87    2.000000
40    2.000000
57    1.000000
49    2.000000
58    2.000000
7     2.000000
88    2.000000
25    2.000000
37    2.000000
64    2.000000
45    2.000000
Name: origin, dtype: float64

In [749]:
from sklearn.preprocessing import StandardScaler

In [750]:
sc=StandardScaler()
sc.fit(x_train)

StandardScaler()

In [751]:
sc.mean_

array([1.26582278e-02, 1.87341772e+01, 6.26582278e+00, 2.48405063e+02,
       1.29941230e+02, 3.30139241e+03, 1.42658228e+01, 7.12531646e+01])

In [752]:
sc.scale_

array([1.11794441e-01, 6.06235293e+00, 1.86716370e+00, 1.25282215e+02,
       4.85189321e+01, 9.77724372e+02, 3.13699389e+00, 1.06102833e+00])

In [753]:
x_train.describe()

name        mpg  cylinders  displacement  horsepower       weight  \
count  79.000000  79.000000  79.000000     79.000000    79.00000    79.000000   
mean    0.012658  18.734177   6.265823    248.405063   129.94123  3301.392405   
std     0.112509   6.101090   1.879095    126.082748    48.82896   983.971875   
min     0.000000   9.000000   3.000000     70.000000    46.00000  1613.000000   
25%     0.000000  14.000000   4.000000    113.000000    88.00000  2373.500000   
50%     0.000000  17.000000   8.000000    302.000000   130.00000  3433.000000   
75%     0.000000  24.000000   8.000000    350.000000   165.00000  4223.000000   
max     1.000000  35.000000   8.000000    455.000000   225.00000  5140.000000   

       acceleration  model_year  
count     79.000000   79.000000  
mean      14.265823   71.253165  
std        3.157039    1.067808  
min        8.000000   70.000000  
25%       12.000000   70.000000  
50%       14.000000   71.000000  
75%       16.000000   72.000000  
max       23.500000   73.000000

In [754]:
x_train_sc = sc.transform(x_train)
x_test_sc = sc.transform(x_test)

In [755]:
x_train

name  mpg  cylinders  displacement  horsepower  weight  acceleration  \
31   0.0   25          4         113.0        95.0    2228          14.0   
17   0.0   21          6         200.0        85.0    2587          16.0   
59   0.0   23          4          97.0        54.0    2254          23.5   
53   0.0   31          4          71.0        65.0    1773          19.0   
13   0.0   14          8         455.0       225.0    3086          10.0   
..   ...  ...        ...           ...         ...     ...           ...   
91   0.0   13          8         400.0       150.0    4464          12.0   
98   0.0   16          6         250.0       100.0    3278          18.0   
67   0.0   11          8         429.0       208.0    4633          11.0   
8    0.0   14          8         455.0       225.0    4425          10.0   
96   1.0   13          8         360.0       175.0    3821          11.0   

    model_year  
31          71  
17          70  
59          72  
53          71  
13          70  
..         ...  
91          73  
98          73  
67          72  
8           70  
96          73  

[79 rows x 8 columns]

In [756]:
x_train_sc

array([[-1.13227703e-01,  1.03356285e+00, -1.21351052e+00,
        -1.08080036e+00, -7.20156611e-01, -1.09784765e+00,
        -8.47380627e-02, -2.38603013e-01],
       [-1.13227703e-01,  3.73753031e-01, -1.42367156e-01,
        -3.86368195e-01, -9.26261724e-01, -7.30668505e-01,
         5.52814981e-01, -1.18108491e+00],
       [-1.13227703e-01,  7.03657942e-01, -1.21351052e+00,
        -1.20851202e+00, -1.56518758e+00, -1.07125529e+00,
         2.94363889e+00,  7.03878887e-01],
       [-1.13227703e-01,  2.02327758e+00, -1.21351052e+00,
        -1.41604348e+00, -1.33847195e+00, -1.56321398e+00,
         1.50914455e+00, -2.38603013e-01],
       [-1.13227703e-01, -7.80914155e-01,  9.28776206e-01,
         1.64903643e+00,  1.95920987e+00, -2.20299720e-01,
        -1.35984415e+00, -1.18108491e+00],
       [-1.13227703e-01,  5.38705486e-01, -1.21351052e+00,
        -1.01694453e+00, -1.11175633e+00, -8.08400023e-01,
         1.19036802e+00,  7.03878887e-01],
       [-1.13227703e-01, -1.440723

In [757]:
x_train_sc = pd.DataFrame(x_train_sc, columns = ['name','mpg','cylinders','displacement','horsepower','weight','acceleration','model_year'])
x_train_sc = pd.DataFrame(x_test_sc, columns = ['name','mpg','cylinders','displacement','horsepower','weight','acceleration','model_year'])

In [758]:
x_train

name  mpg  cylinders  displacement  horsepower  weight  acceleration  \
31   0.0   25          4         113.0        95.0    2228          14.0   
17   0.0   21          6         200.0        85.0    2587          16.0   
59   0.0   23          4          97.0        54.0    2254          23.5   
53   0.0   31          4          71.0        65.0    1773          19.0   
13   0.0   14          8         455.0       225.0    3086          10.0   
..   ...  ...        ...           ...         ...     ...           ...   
91   0.0   13          8         400.0       150.0    4464          12.0   
98   0.0   16          6         250.0       100.0    3278          18.0   
67   0.0   11          8         429.0       208.0    4633          11.0   
8    0.0   14          8         455.0       225.0    4425          10.0   
96   1.0   13          8         360.0       175.0    3821          11.0   

    model_year  
31          71  
17          70  
59          72  
53          71  
13          70  
..         ...  
91          73  
98          73  
67          72  
8           70  
96          73  

[79 rows x 8 columns]

In [759]:
x_train_sc.head()

name       mpg  cylinders  displacement  horsepower    weight  \
0 -0.113228  0.043848  -0.142367      0.012731   -0.617104 -0.019834   
1 -0.113228 -0.615962   0.928776      1.210028    0.413422  0.470079   
2 -0.113228  0.373753  -1.213511     -1.008963   -0.905651 -1.099893   
3 -0.113228  1.198515  -1.213511     -1.016945   -0.349167 -1.091711   
4 -0.113228 -0.945867   0.928776      1.210028    1.237842  1.146139   

   acceleration  model_year  
0      0.234038   -0.238603  
1     -1.519232   -1.181085  
2      0.712203    0.703879  
3     -0.562903   -1.181085  
4     -0.562903    0.703879

In [760]:
x_train_sc.describe()

name        mpg  cylinders  displacement  horsepower  \
count  2.000000e+01  20.000000  20.000000     20.000000   20.000000   
mean  -1.132277e-01  -0.244819   0.071862      0.162992    0.042432   
std    1.423831e-17   0.764151   0.958060      0.915712    0.876779   
min   -1.132277e-01  -1.440724  -1.213511     -1.204521   -1.029314   
25%   -1.132277e-01  -0.822152  -1.213511     -0.901206   -0.642867   
50%   -1.132277e-01  -0.451009   0.393205      0.252190   -0.101841   
75%   -1.132277e-01   0.250039   0.928776      0.836870    0.485558   
max   -1.132277e-01   1.198515   0.928776      1.529307    1.753105   

          weight  acceleration  model_year  
count  20.000000     20.000000   20.000000  
mean    0.153528     -0.100677    0.091266  
std     0.954338      0.782379    0.879620  
min    -1.202172     -1.838009   -1.181085  
25%    -0.946987     -0.443362   -0.238603  
50%     0.249158     -0.164432   -0.238603  
75%     0.912433      0.393427    0.703879  
max     1.477520      1.668533    1.646361

In [761]:
x_train_sc.describe().round(2)

name    mpg  cylinders  displacement  horsepower  weight  \
count  20.00  20.00      20.00         20.00       20.00   20.00   
mean   -0.11  -0.24       0.07          0.16        0.04    0.15   
std     0.00   0.76       0.96          0.92        0.88    0.95   
min    -0.11  -1.44      -1.21         -1.20       -1.03   -1.20   
25%    -0.11  -0.82      -1.21         -0.90       -0.64   -0.95   
50%    -0.11  -0.45       0.39          0.25       -0.10    0.25   
75%    -0.11   0.25       0.93          0.84        0.49    0.91   
max    -0.11   1.20       0.93          1.53        1.75    1.48   

       acceleration  model_year  
count         20.00       20.00  
mean          -0.10        0.09  
std            0.78        0.88  
min           -1.84       -1.18  
25%           -0.44       -0.24  
50%           -0.16       -0.24  
75%            0.39        0.70  
max            1.67        1.65

# Implement Model

# Model = RandomForestRegression

In [762]:
from sklearn.ensemble import RandomForestRegressor

In [763]:
regressor =RandomForestRegressor(criterion='squared_error')
regressor.fit(x_train,y_train)

RandomForestRegressor()

In [764]:
regressor =RandomForestRegressor(n_estimators=40)
regressor.fit(x_train,y_train)

RandomForestRegressor(n_estimators=40)

In [765]:
regressor.score(x_test,y_test)

0.6079998768251373

In [766]:
y_pred=regressor.predict(x_test)
regressor.predict(x_test)

array([2.        , 2.        , 1.81060606, 1.62651515, 2.        ,
       2.        , 2.        , 2.        , 2.        , 2.        ,
       2.        , 1.17348485, 1.76439394, 1.61666667, 2.        ,
       2.        , 2.        , 2.        , 2.        , 2.        ])

In [767]:
x_test.iloc[-1,:]

name               0.0
mpg               18.0
cylinders          6.0
displacement     258.0
horsepower       110.0
weight          2962.0
acceleration      13.5
model_year        71.0
Name: 45, dtype: float64

In [768]:
y_pred=regressor.predict(x_test)
regressor.predict(x_test)

array([2.        , 2.        , 1.81060606, 1.62651515, 2.        ,
       2.        , 2.        , 2.        , 2.        , 2.        ,
       2.        , 1.17348485, 1.76439394, 1.61666667, 2.        ,
       2.        , 2.        , 2.        , 2.        , 2.        ])

In [769]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [770]:
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 0.06513357256778299


In [771]:
print("MSE",mean_squared_error(y_test,y_pred))

MSE 0.018568426887230337


In [772]:
import numpy as np
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE 0.13626601515869735


In [773]:
print("R_Squared",r2_score(y_test,y_pred))

R_Squared 0.6079998768251373


# Implement model= Simple linear Regression

In [774]:
# Fitting the Simple Linear Regression model to the tratre
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [775]:
y_pred= regressor.predict(x_test)
x_pred= regressor.predict(x_train)

In [776]:
regressor.intercept_

4.165644670883897

In [777]:
regressor.score(x_test, y_test)

-0.1957405665443892

# Implement model = Ridge and Lasso

In [778]:
from sklearn.linear_model import Ridge, Lassoa


In [779]:
rd = Ridge()

rd.fit(x_train,y_train)


Ridge()

In [780]:

rd = Ridge()

rd.fit(x_train, y_train)
rd.score(x_test, y_test)

-0.19287451520229015

In [781]:
Is = Lasso()

Is.fit(x_train, y_train)
Is.score(x_test, y_test)

-0.14709889933828268

In [782]:
rd2=Ridge(alpha=2) # if you increase alpha value
rd2.fit(x_train,y_train)
rd2.score(x_test,y_test)

-0.1907769861542703

In [783]:
ls2=Lasso(alpha=2) # if you increase alpha value
ls2.fit(x_train,y_train)
ls2.score(x_test,y_test)

-0.1724777758020566

# Implement k-Fold model

In [697]:

from sklearn.model_selection import cross_val_score

In [698]:
score_rf=cross_val_score(RandomForestRegressor(n_estimators=5),x_train,y_train,cv=5)
print(score_rf)
print("Avg:",np.average(score_rf))

[0.58805759 0.11690879 0.18388235 0.31524144 0.38890159]
Avg: 0.31859835047703455


# Implement Decision Tree model

In [703]:
from sklearn.tree import DecisionTreeRegressor

In [704]:
regressor = DecisionTreeRegressor(criterion='squared_error')
regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [705]:
regressor.score(x_test,y_test)

0.9654465978229932